version: "3.9"

services:
  db:
    image: postgres:16
    container_name: progresstracker_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progresstracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
