"""Rename name_pt to name in exercises

Revision ID: 366abfaf60c8
Revises: 1206876b2821
Create Date: 2025-08-08 22:25:37.527796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366abfaf60c8'
down_revision: Union[str, Sequence[str], None] = '1206876b2821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_exercises_name_en'), table_name='exercises')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.drop_column('exercises', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.create_index(op.f('ix_exercises_name_en'), 'exercises', ['name_en'], unique=False)
    op.drop_column('exercises', 'name')
    # ### end Alembic commands ###
