"""Refactor Exercise model to English-only name and enums

Revision ID: 3bea2d905dda
Revises: 366abfaf60c8
Create Date: 2025-08-17 21:24:49.028185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bea2d905dda'
down_revision: Union[str, Sequence[str], None] = '366abfaf60c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
