"""add order field to exercise_session model

Revision ID: 839d25f8d1b2
Revises: f633ad21cbdd
Create Date: 2025-10-14 18:24:52.511317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839d25f8d1b2'
down_revision: Union[str, Sequence[str], None] = 'f633ad21cbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_sessions', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_sessions', 'order')
    # ### end Alembic commands ###
