"""add user_id to template model

Revision ID: 91274a85defd
Revises: a0a7a9212e73
Create Date: 2025-10-04 20:02:11.683923

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91274a85defd"
down_revision: Union[str, Sequence[str], None] = "a0a7a9212e73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "templates", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.drop_column("templates", "user_id")
    # ### end Alembic commands ###
