"""add description field to template model

Revision ID: f633ad21cbdd
Revises: 6aaffe864b1c
Create Date: 2025-10-14 18:23:34.320338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f633ad21cbdd'
down_revision: Union[str, Sequence[str], None] = '6aaffe864b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'description')
    # ### end Alembic commands ###
