"""add order fields to ExerciseSession and Set models

Revision ID: be0a97f219e8
Revises: f633ad21cbdd
Create Date: 2025-10-15 19:06:11.564566

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0a97f219e8"
down_revision: Union[str, Sequence[str], None] = "f633ad21cbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercise_sessions", "order", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column("sets", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Backfill existing records with id-based order
    op.execute('UPDATE exercise_sessions SET "order" = id WHERE "order" IS NULL')
    op.execute('UPDATE sets SET "order" = id WHERE "order" IS NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sets", "order")
    op.alter_column(
        "exercise_sessions", "order", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
