"""add is_global field to templates and make user_id nullable

Revision ID: deed8a0b948e
Revises: ca2890303be8
Create Date: 2025-10-21 22:02:48.489426

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "deed8a0b948e"
down_revision: Union[str, Sequence[str], None] = "ca2890303be8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("is_global", sa.Boolean(), nullable=False))
    op.alter_column("templates", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("templates", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("templates", "is_global")
    # ### end Alembic commands ###
